// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;

import java.time.LocalDate;

import EchoConnect.Person.Customer;


/************************************************************/
/**
 * 
 */
public class Notifications {
	private Billing billing;
	private Payment Payment;
	private int lastCustomerId = 0;
	
	public Notifications(Billing billing, EchoConnect.Payment Payment) {
        this.billing = billing;
        this.Payment = Payment;
    }
	/**
	 * 
	 */
	public void PaymentReminder() {
		LocalDate today = LocalDate.now();
	    LocalDate dueDate = billing.getDueDate();
	    LocalDate billDate = billing.getBillDate();

	        if (billDate.equals(today)) {
	            double dueAmount = billing.getDueAmount();
	            System.out.println("New bill generation: Your bill of $" + dueAmount + " has been generated.");
	        }

	        LocalDate remainderDate = dueDate.minusDays(5);
	        if (today.equals(remainderDate)) {
	            double dueAmount = billing.getDueAmount();
	            System.out.println("Payment reminder: Your bill of $" + dueAmount + " is due in 5 days.");
	        }
	}

	/**
	 * 
	 */
	public void WelcomeEmail(Customer customer) {
		 if (customer != null && customer.getCustomerId() > lastCustomerId) {
	            System.out.println("New Customer ID is generated: " + customer.getCustomerId());
	            System.out.println("Welcome to Echo Connect: A Telecom Service Company.");
	        }
	}

	/**
	 * 
	 */
	public void SuccessfulPayment(Payment payment) {
		if (payment.getPaymentStatus().equals("Success")) {
            System.out.println("Payment Successful,Thank you");
        }
	}

	/**
	 * 
	 */
	public void PromotionEmail() {
		System.out.println("Promotion Email Sent");
		
	}

	/**
	 * 
	 */
	public void OverdueReminder() {
		System.out.println("Overdue Reminder Sent,Thank you");
	}

	/**
	 * 
	 */
	public void TicketStatus() {
		System.out.println("Ticket Status Sent,Thank you");
	}
}
