// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;

import java.util.Date;
import java.util.Scanner;


public class Payment {
	public int PaymentID;
	public String PaymentStatus;
	public Date PaymentDate;
	public String PaymentMethod;
	public String PaymentPreference;
	/**
	 * Setting Default method between card, bank and wallet
	 */
	public void SetDefaultMethod() {
		switch (PaymentPreference.toLowerCase())
		{
		case "credit card":
			PaymentMethod = "Credit Card";
			break;
		case "bank transfer":
			PaymentMethod = "Bank Transfer";
			break;
		case "wallet":
			PaymentMethod = "Wallet";
			break;
		default:
			PaymentMethod = "Unknown";
			break;
		}
		
		System.out.println("Setting default payment method to: "+ PaymentMethod);
		
	}

	/**
	 * Initiating Payment
	 */
	public void InitiatePayment() {
		//Displaying options to the user
		System.out.println("Choose an option");
		System.out.println("1. Pay Using default payment method");
		System.out.println("2. Go to individual payment methods");
		
		// Get user input
		Scanner scanner = new Scanner(System.in);
		int userChoice = scanner.nextInt();
		
		switch(userChoice)
		{
		case 1:
			System.out.println("Paying Using default payment method: "+ PaymentMethod);
			PaymentStatus = "Completed";
			break;
		case 2:
			//Navigate to individual payment methods
			NavigateToPaymentMethods();
			break;
		default:
			System.out.println("Invalid Choice");
		}
	}
	
	private void NavigateToPaymentMethods() {
		System.out.println("Navigating to individual payment methods menu");
		System.out.println("1. Card");
		System.out.println("2. Wallet");
		System.out.println("3. Bank");
		
		Scanner scanner = new Scanner(System.in);
		int userChoice = scanner.nextInt();
		
		switch (userChoice)
		{
		case 1:
			Card.ManageCards();
			break;
		case 2:
			Wallet.RedirectToVendor("WalletVendor");
			PaymentStatus = "Completed";
			break;
		case 3:
			Bank.RedirectToVendor("BankVendor");
			PaymentStatus = "Completed";
			break;
		default:
			System.out.println("Invalid Choice");
		}
	}

	
	/**
	 *  Constructor
	 */
	
	public Payment(int paymentID, String paymentStatus, Date paymentDate, String paymentMethod, String paymentPreference)
	{
		this.PaymentID = paymentID;
		this.PaymentStatus = paymentStatus;
		this.PaymentDate = paymentDate;
		this.PaymentMethod = paymentMethod;
		this.PaymentPreference = paymentPreference;
	}
	

	public String getPaymentStatus() {
		// TODO Auto-generated method stub
		return PaymentStatus;
	}
	
}
