// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;

/************************************************************/
/**
 * 
 */
public class Plan {
	/**
	 * 
	 */
	public int PlanID;
	/**
	 * 
	 */
	public String PlanName;
	/**
	 * 
	 */
	public int PlanCost;
	/**
	 * 
	 */
	public String PlanDescription;

	/**
	 * 
	 */
	public void ViewPlan() {System.out.println("view plan");
	}
}
