// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;

import java.util.HashMap;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class Promotions {
	
	private Map<String, String> promoCodes;  // Map to store promo codes and their descriptions
    public Promotions() {
        this.promoCodes = new HashMap<>();
    }
	public String PromoCode;
	public String PromoDesc;
	public void UsePromo(String promoCode) {
        if (promoCodes.containsKey(promoCode)) {
            System.out.println("Promo code applied successfully!");
            System.out.println("Promo Description: " + promoCodes.get(promoCode));
        } else {
            System.out.println("Invalid promo code. Please enter a valid one.");
        }
    }
	public void AddPromo(String promoCode, String promoDesc) {
        if (!promoCodes.containsKey(promoCode)) {
            promoCodes.put(promoCode, promoDesc);
            System.out.println("Promo code added successfully!");
        } else {
            System.out.println("Promo code already exists. Cannot add duplicate promo codes.");
        }
    }
	public void RemovePromo(String promoCode) {
        if (promoCodes.containsKey(promoCode)) {
            promoCodes.remove(promoCode);
            System.out.println("Promo code removed successfully!");
        } else {
            System.out.println("Promo code not found. Cannot remove non-existing promo code.");
        }
    }
}
