// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Resources {
	/**
	 * 
	 */
	public List FAQ;

	/**
	 * 
	 */
	public void ViewFAQ() {
	    System.out.println("Viewing Frequently Asked Questions (FAQs)...");

	}

	/**
	 * 
	 */
	public void RedirectToSupport() {
	    System.out.println("Redirecting to support...");

	}

	/**
	 * 
	 */
	public void AddFAQ() {
	    System.out.println("Adding new Frequently Asked Question (FAQ)...");

	}
}
