// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;

import java.util.Date;
import java.util.List;
import EchoConnect.Person.Customer;

public class Services {
	
	private int serviceID;
	private String serviceName;
	private java.util.Date startDate;
	private java.util.Date endDate;
	
	public static void viewAllServices() {
		Services mobilityPlan = new Services(1, "MobilityPlan", new java.util.Date(), new java.util.Date());
		Services wifi = new Services(2, "Wifi", new java.util.Date(), new java.util.Date());
		Services tv = new Services(3, "TV", new java.util.Date(), new java.util.Date());
		Services bundle = new Services(4, "Bundle", new java.util.Date(), new java.util.Date());
	
		System.out.println("All Services:");
		System.out.println("--------------------------");
		printServiceDetails(mobilityPlan);
		printServiceDetails(wifi);
		printServiceDetails(tv);
		printServiceDetails(bundle);
		System.out.println("--------------------------");
	}
	
	public void subscribe(String serviceName, List<String> myServices) {
		System.out.println("Subscribed to " + serviceName);
		myServices.add(serviceName);
	}
	
	public void unsubscribe(String serviceName, List<String> myServices) {
		System.out.println("Unsubscribed from " + serviceName);
		myServices.remove(serviceName);
	
	}
	public static void viewService(String serviceName) {
		System.out.println("Viewing details for service: " + serviceName);
		printServiceDetails(serviceName);
	}
	
	
	public Services() {}
	
	
	public Services(int serviceID, String serviceName, java.util.Date startDate, java.util.Date endDate) {
		this.serviceID = serviceID;
		this.serviceName = serviceName;
		this.startDate = startDate;
		this.endDate = endDate;
		Mobility Plans = new Mobility();
		Customer customer = new Person().new Customer();
		List<Services> myServices = customer.getMyServices();
	}
	
	public int getServiceID() {
		return serviceID;
	}
	
	public String getServiceName() {
		return serviceName;
	}
	
	public java.util.Date getStartDate() {
		return startDate;
	}
	
	public java.util.Date getEndDate() {
		return endDate;
	}
	
	public void upgradeService(String serviceName) {
		System.out.println("Upgraded " + serviceName + " service");
	
	}
	
	public void downgradeService(String serviceName) {
		System.out.println("Downgraded " + serviceName + " service");
	
	}
	
	public void cancelAllService() {
		System.out.println("Canceled All service");
		
	
	}
	
	
	
	public static void printServiceDetails(String serviceName2) {
	//	System.out.println("Service ID: " + serviceName2.getServiceID());
	//	System.out.println("Service Name: " + serviceName2.getServiceName());
	//	System.out.println("Start Date: " + serviceName2.getStartDate());
	//	System.out.println("End Date: " + serviceName2.getEndDate());
		System.out.println("--------------------------");
	}
};
