// --------------------------------------------------------
// Code generated by Papyrus Java

// --------------------------------------------------------

package EchoConnect;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Support {
	
	 public List<String> SupportEmployees;
	 public List<String> SupportManagers;
	 public List<Ticket> Tickets;
	
	 public Support() {
	        this.SupportEmployees = new ArrayList<>();
	        this.SupportManagers = new ArrayList<>();
	        this.Tickets = new ArrayList<>();
	    }
	 
	public void ViewAllTickets() {
		for (Ticket ticket : Tickets) {
            System.out.println("Ticket ID: " + ticket.TicketID +
                    ", Status: " + ticket.TicketStatus +
                    ", Priority: " + ticket.TicketPriority);
        }
	}

	/**
	 * 
	 */
	public void AccessTicket() {
		System.out.println("Accessing ticket...");
	}

	/**
	 * 
	 */
	public void FilterTickets() {
		System.out.println("Filtering tickets...");
	}
}
