// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EchoConnect;
import EchoConnect.Payment;

/************************************************************/
/**
 * 
 */
public class Wallet {
	
	/**
	 * 
	 */
	public int WalletID;
	/**
	 * 
	 */
	public String WalletName;

	/**
	 * 
	 */
	public void SaveWalletInfo() {
		System.out.println("Wallet Info Saved");
	}
	
	static void RedirectToVendor (String vendorName)
	{
		System.out.println("Redirecting to "+ vendorName + " webpage");
		
	}
	/**
	 * 
	 */
//	public void RedirectToWallet() {
//	}
}
